name: VariousEnchantments
version: '${project.version}'
main: ru.dodabyte.variousenchantments.VariousEnchantmentsMain
api-version: '1.20'
commands:
  variousenchantments:
    aliases:
      - ves
    description: "General information about the plugin."
  variousenchant:
    aliases:
      - ve
      - venchant
    description: "Enchant the item that is in the main hand."
  variousenchantgui:
    aliases:
      - veg
    description: "Open the Enchantment menu."